# Generated by Django 5.0.3 on 2024-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=100)),
                ("price", models.CharField(db_column="price", max_length=200)),
                ("owner", models.CharField(db_column="owner", max_length=100)),
                ("nikcname", models.CharField(db_column="nikcname", max_length=200)),
                ("mobile", models.CharField(db_column="mobile", max_length=100)),
                ("catagory", models.CharField(db_column="catagory", max_length=200)),
                ("status", models.CharField(db_column="status", max_length=100)),
                (
                    "image",
                    models.CharField(db_column="image", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Market",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Found",
        ),
        migrations.DeleteModel(
            name="Lost",
        ),
    ]
