# Generated by Django 5.0.3 on 2024-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_market_delete_found_delete_lost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Found",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "found_name",
                    models.CharField(db_column="found_name", max_length=100),
                ),
                ("place", models.CharField(db_column="address", max_length=200)),
                ("found_date", models.DateField(db_column="found_date")),
                ("username", models.CharField(db_column="username", max_length=100)),
                ("mobile", models.CharField(db_column="mobile", max_length=100)),
                ("is_return", models.CharField(db_column="is_return", max_length=100)),
                (
                    "image",
                    models.CharField(db_column="image", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Found",
                "managed": True,
            },
        ),
    ]
