# Generated by Django 5.0.3 on 2024-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_found"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="imageUrl",
            field=models.CharField(db_column="imageUrl", max_length=200, null=True),
        ),
    ]
